Added check for dependencies

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,7 +7,12 @@ before_install:
       rvm use 2.2;
       gem install hiptest-publisher;
     fi;
-script: mvn -B verify -Dvaadin.productionMode -Dcom.vaadin.testbench.Parameters.testsInParallel=2 -Dvaadin.proKey=$VAADIN_PRO_KEY -Dsauce.user=$SAUCE_USER -Dsauce.sauceAccessKey=$SAUCE_ACCESSKEY
+script:
+  - if mvn dependency:tree | grep -B3 "version selected from constraint"; then
+      echo "Error: Have found versions that are selected from constraint, pin those so they won't change themselves.";
+      exit 1;
+    fi;
+  - mvn -B verify -Dvaadin.productionMode -Dcom.vaadin.testbench.Parameters.testsInParallel=2 -Dvaadin.proKey=$VAADIN_PRO_KEY -Dsauce.user=$SAUCE_USER -Dsauce.sauceAccessKey=$SAUCE_ACCESSKEY
 after_script:
   - if [[ $TRAVIS_PULL_REQUEST == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
         sh publishHiptestResults.sh $HIPTEST_SECRET $HIPTEST_TEST_RUN;
